In [1]:
import pandas as pd
import os
import numpy as np
os.getcwd()

'C:\\Users\\taohuang\\Downloads\\gcp-main(3)\\gcp-main'

In [2]:
gcp=pd.read_csv(r'gcp_epsg32611_2021_los1_latlon.csv')
gcp['z'].describe()

count      13.000000
mean     1622.576615
std         2.856767
min      1617.385000
25%      1621.089000
50%      1622.351000
75%      1624.507000
max      1627.889000
Name: z, dtype: float64

In [3]:
camera=pd.read_csv(r'C:\Users\taohuang\Documents\Tao\ARS\los_exif\20210428_exif_jpg.csv')
camera['AbsoluteAltitude'].describe()

count     556.000000
mean     1565.736259
std         5.322228
min      1553.310000
25%      1562.010000
50%      1565.810000
75%      1569.615000
max      1577.830000
Name: AbsoluteAltitude, dtype: float64

In [5]:
camera=pd.read_csv(r'C:\Users\taohuang\Documents\Tao\ARS\los_exif\20210519_exif_jpg.csv')
camera['AbsoluteAltitude'].describe()

count     836.000000
mean     1718.244175
std         5.538007
min      1704.420000
25%      1714.095000
50%      1718.670000
75%      1722.470000
max      1729.930000
Name: AbsoluteAltitude, dtype: float64

In [6]:
camera=pd.read_csv(r'C:\Users\taohuang\Documents\Tao\ARS\los_exif\20210602_exif_jpg.csv')
camera['AbsoluteAltitude'].describe()

count     853.000000
mean     1641.267456
std         3.573551
min      1631.170000
25%      1638.880000
50%      1641.540000
75%      1643.840000
max      1649.530000
Name: AbsoluteAltitude, dtype: float64

In [21]:
#new GCP z= GCP z- max(gcp above camera)-max(fly height)
#max(gcp above camera)=max(gcp z)-min(camera z)
#max(fly height)=max(GCP z)-min(camera z)
gcp['z_2']=gcp['z']-(max(gcp['z'])-min(camera['AbsoluteAltitude']))- (max(gcp['z'])-min(camera['AbsoluteAltitude']))
gcp

,label,x,y,z,x_uncertainty,y_uncertainty,z_uncertainty,lon,lat,z_2,z_3
0,1,521526.515,4776759.933,1622.351,0.001530,0.002094,0.002521,-116.735282,43.143279,1473.193,1508.670287
1,2,521496.582,4776756.760,1623.073,0.001755,0.002633,0.003413,-116.735650,43.143252,1473.915,1509.392287
2,3,521495.418,4776702.869,1627.889,0.001586,0.002316,0.002635,-116.735667,43.142766,1478.731,1514.208287
3,4,521414.463,4776694.543,1624.507,0.001630,0.002124,0.002553,-116.736663,43.142694,1475.349,1510.826287
4,5,521437.505,4776719.279,1624.717,0.001432,0.001894,0.002224,-116.736378,43.142916,1475.559,1511.036287
5,6,521415.776,4776759.460,1621.785,0.001583,0.002438,0.002617,-116.736644,43.143278,1472.627,1508.104287
6,7,521388.898,4776759.408,1621.089,0.001418,0.002184,0.002323,-116.736975,43.143279,1471.931,1507.408287
7,8,521410.759,4776815.274,1617.385,0.001156,0.001792,0.001863,-116.736704,43.143781,1468.227,1503.704287
8,9,521433.109,4776798.957,1620.489,0.001997,0.003129,0.003202,-116.736429,43.143633,1471.331,1506.808287
9,10,521470.082,4776800.927,1621.179,0.001299,0.002035,0.002074,-116.735975,43.143650,1472.021,1507.498287
10,11,521490.479,4776814.980,1619.710,0.002259,0.003600,0.003590,-116.735723,43.143776,1470.552,1506.029287
11,12,521449.432,4776757.830,1622.649,0.001707,0.002389,0.002577,-116.736230,43.143263,1473.491,1508.968287
12,13,521473.725,4776718.991,1626.673,0.001499,0.002169,0.002067,-116.735933,43.142912,1477.515,1512.992287

In [22]:
#new GCP z= GCP z- mean(gcp above camera)-mean(fly height)
#mean(gcp above camera)=mean(gcp z)-mean(camera z)
#mean(fly height)=mean(GCP z)-mean(camera z)
gcp['z_3']=gcp['z']-((gcp['z'].mean())- (camera['AbsoluteAltitude'].mean()))- ( (gcp['z'].mean())- (camera['AbsoluteAltitude'].mean()))
gcp

,label,x,y,z,x_uncertainty,y_uncertainty,z_uncertainty,lon,lat,z_2,z_3
0,1,521526.515,4776759.933,1622.351,0.001530,0.002094,0.002521,-116.735282,43.143279,1473.193,1508.670287
1,2,521496.582,4776756.760,1623.073,0.001755,0.002633,0.003413,-116.735650,43.143252,1473.915,1509.392287
2,3,521495.418,4776702.869,1627.889,0.001586,0.002316,0.002635,-116.735667,43.142766,1478.731,1514.208287
3,4,521414.463,4776694.543,1624.507,0.001630,0.002124,0.002553,-116.736663,43.142694,1475.349,1510.826287
4,5,521437.505,4776719.279,1624.717,0.001432,0.001894,0.002224,-116.736378,43.142916,1475.559,1511.036287
5,6,521415.776,4776759.460,1621.785,0.001583,0.002438,0.002617,-116.736644,43.143278,1472.627,1508.104287
6,7,521388.898,4776759.408,1621.089,0.001418,0.002184,0.002323,-116.736975,43.143279,1471.931,1507.408287
7,8,521410.759,4776815.274,1617.385,0.001156,0.001792,0.001863,-116.736704,43.143781,1468.227,1503.704287
8,9,521433.109,4776798.957,1620.489,0.001997,0.003129,0.003202,-116.736429,43.143633,1471.331,1506.808287
9,10,521470.082,4776800.927,1621.179,0.001299,0.002035,0.002074,-116.735975,43.143650,1472.021,1507.498287
10,11,521490.479,4776814.980,1619.710,0.002259,0.003600,0.003590,-116.735723,43.143776,1470.552,1506.029287
11,12,521449.432,4776757.830,1622.649,0.001707,0.002389,0.002577,-116.736230,43.143263,1473.491,1508.968287
12,13,521473.725,4776718.991,1626.673,0.001499,0.002169,0.002067,-116.735933,43.142912,1477.515,1512.992287

In [23]:
#new GCP z= GCP z- mean(gcp above camera)-mean(fly height)
#mean(gcp above camera)=mean(gcp z)-mean(camera z)
#mean(fly height)=25
gcp['z_4']=gcp['z']-((gcp['z'].mean())- (camera['AbsoluteAltitude'].mean()))- ( 25)
gcp

,label,x,y,z,x_uncertainty,y_uncertainty,z_uncertainty,lon,lat,z_2,z_3,z_4
0,1,521526.515,4776759.933,1622.351,0.001530,0.002094,0.002521,-116.735282,43.143279,1473.193,1508.670287,1540.510644
1,2,521496.582,4776756.760,1623.073,0.001755,0.002633,0.003413,-116.735650,43.143252,1473.915,1509.392287,1541.232644
2,3,521495.418,4776702.869,1627.889,0.001586,0.002316,0.002635,-116.735667,43.142766,1478.731,1514.208287,1546.048644
3,4,521414.463,4776694.543,1624.507,0.001630,0.002124,0.002553,-116.736663,43.142694,1475.349,1510.826287,1542.666644
4,5,521437.505,4776719.279,1624.717,0.001432,0.001894,0.002224,-116.736378,43.142916,1475.559,1511.036287,1542.876644
5,6,521415.776,4776759.460,1621.785,0.001583,0.002438,0.002617,-116.736644,43.143278,1472.627,1508.104287,1539.944644
6,7,521388.898,4776759.408,1621.089,0.001418,0.002184,0.002323,-116.736975,43.143279,1471.931,1507.408287,1539.248644
7,8,521410.759,4776815.274,1617.385,0.001156,0.001792,0.001863,-116.736704,43.143781,1468.227,1503.704287,1535.544644
8,9,521433.109,4776798.957,1620.489,0.001997,0.003129,0.003202,-116.736429,43.143633,1471.331,1506.808287,1538.648644
9,10,521470.082,4776800.927,1621.179,0.001299,0.002035,0.002074,-116.735975,43.143650,1472.021,1507.498287,1539.338644
10,11,521490.479,4776814.980,1619.710,0.002259,0.003600,0.003590,-116.735723,43.143776,1470.552,1506.029287,1537.869644
11,12,521449.432,4776757.830,1622.649,0.001707,0.002389,0.002577,-116.736230,43.143263,1473.491,1508.968287,1540.808644
12,13,521473.725,4776718.991,1626.673,0.001499,0.002169,0.002067,-116.735933,43.142912,1477.515,1512.992287,1544.832644

In [24]:
gcp.to_csv(r'gcp_epsg32611_2021_los1_latlon_20220718.csv',index=False)