In [1]:
from dbfread import DBF
import pandas as pd

In [2]:
dbf = DBF(r'C:\Users\taohuang\Downloads\uavgcp2.dbf')
dbf

In [3]:
frame = pd.DataFrame(iter(dbf))
frame

,OBJNAME,lat,lon,ele,x,y,z
0,100,43.126072,-116.753781,1648.761454,520027.813239,4.774844e+06,1648.761454
1,101,43.125312,-116.753858,1650.799164,520021.796079,4.774760e+06,1650.799164
2,103,43.125003,-116.753832,1652.655994,520024.063315,4.774726e+06,1652.655994
3,104,43.124862,-116.753561,1655.960181,520046.143612,4.774710e+06,1655.960181
4,105,43.125067,-116.753444,1656.049297,520055.533874,4.774733e+06,1656.049297
5,106,43.124708,-116.754546,1646.540785,519966.066523,4.774693e+06,1646.540785
6,107,43.124951,-116.754620,1645.627267,519959.959181,4.774720e+06,1645.627267
7,108,43.125204,-116.754399,1645.994283,519977.872625,4.774748e+06,1645.994283
8,110,43.125309,-116.754132,1648.217930,519999.552847,4.774760e+06,1648.217930
9,111,43.126643,-116.754662,1646.184558,519956.002971,4.774908e+06,1646.184558
10,112,43.126913,-116.754555,1646.216314,519964.595395,4.774938e+06,1646.216314
11,114,43.127238,-116.754286,1642.440314,519986.355739,4.774974e+06,1642.440314
12,115,43.127359,-116.754574,1644.616432,519962.911986,4.774987e+06,1644.616432
13,116,43.127273,-116.754887,1646.002864,519937.447403,4.774978e+06,1646.002864
14,117,43.127570,-116.755466,1642.578320,519890.278388,4.775010e+06,1642.578320
15,118,43.127083,-116.755644,1643.136184,519875.985945,4.774956e+06,1643.136184
16,119,43.126710,-116.755350,1645.028249,519899.973302,4.774915e+06,1645.028249
17,120,43.127003,-116.754927,1646.856229,519934.341177,4.774948e+06,1646.856229

In [4]:
frame["ele"].mean()

1647.425878777778

In [6]:
frame.to_csv(r'C:\Users\taohuang\Downloads\uavgcp2.csv')